### PR TITLE
Have virtualbox-hostonly-cidr only apply to virtualbox provider

### PR DESCRIPTION
**Pull request by twardnw**

### CODE REVIEW

**Comment by rtprio** [comment]
i was able to create `xhyve` provider without it being contaminated with `virtualbox` arguments.

**Review by Schnitzel — APPROVED** [review]
looks good!

**Comment by back-2-95** [comment]
Tested it and worked fine!

**Review by rtprio — APPROVED** [review]

**Comment by back-2-95** [comment]
When is this available via Brew?

**Comment by twardnw** [comment]
We will release it as part of our maintenance and release window tomorrow.

On Aug 7, 2017 03:57, "Marko Korhonen" <notifications@github.com> wrote:

When is this available via Brew?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amazeeio/cachalot/pull/5#issuecomment-320633805>, or mute
the thread

**Pull request merged**
